import React, { useState } from 'react';
import { UserProfile, UserConstraints, Equipment, ExpertSystemResult } from '@/types/expertSystem';
import { InferenceEngine } from '@/lib/inferenceEngine';
import { ProgressBar } from '@/components/wizard/ProgressBar';
import { WizardNavigation } from '@/components/wizard/WizardNavigation';
import { Step1Profile } from '@/components/wizard/Step1Profile';
import { Step2Constraints } from '@/components/wizard/Step2Constraints';
import { Step3Equipment } from '@/components/wizard/Step3Equipment';
import { LoadingScreen } from '@/components/wizard/LoadingScreen';
import { MetricCard } from '@/components/dashboard/MetricCard';
import { WorkoutSchedule } from '@/components/dashboard/WorkoutSchedule';
import { InferenceLog } from '@/components/dashboard/InferenceLog';
import { CalculationBreakdown } from '@/components/dashboard/CalculationBreakdown';
import { Dumbbell, Activity, Flame, Brain, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';

const steps = [
  { label: 'Profile', description: 'Experience & Goals' },
  { label: 'Constraints', description: 'Time & Limitations' },
  { label: 'Equipment', description: 'Available Gear' },
];

const Index = () => {
  const [currentStep, setCurrentStep] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<ExpertSystemResult | null>(null);
  const [logExpanded, setLogExpanded] = useState(true);

  const [profile, setProfile] = useState<UserProfile>({
    experienceLevel: null,
    trainingGoal: null,
  });

  const [constraints, setConstraints] = useState<UserConstraints>({
    trainingDays: null,
    availableTime: null,
    intensity: null,
    injuries: ['none'],
  });

  const [equipment, setEquipment] = useState<Equipment>({
    dumbbells: false,
    bands: false,
    bench: false,
    pullupBar: false,
    bodyweight: true,
  });

  const canProceed = (): boolean => {
    switch (currentStep) {
      case 0:
        return !!(profile.experienceLevel && profile.trainingGoal);
      case 1:
        return !!(constraints.trainingDays && constraints.availableTime && constraints.intensity);
      case 2:
        return Object.values(equipment).some(Boolean);
      default:
        return false;
    }
  };

  const handleNext = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleSubmit = () => {
    setIsLoading(true);
  };

  const handleLoadingComplete = () => {
    const engine = new InferenceEngine();
    const engineResult = engine.run(profile, constraints, equipment);
    setResult(engineResult);
    setIsLoading(false);
  };

  const handleReset = () => {
    setCurrentStep(0);
    setResult(null);
    setProfile({ experienceLevel: null, trainingGoal: null });
    setConstraints({ trainingDays: null, availableTime: null, intensity: null, injuries: ['none'] });
    setEquipment({ dumbbells: false, bands: false, bench: false, pullupBar: false, bodyweight: true });
  };

  // Loading screen
  if (isLoading) {
    return <LoadingScreen onComplete={handleLoadingComplete} />;
  }

  // Results dashboard
  if (result) {
    return (
      <div className="min-h-screen bg-background py-8 px-4">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <div className="flex items-center justify-center gap-3 mb-4">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary to-cyan-400 flex items-center justify-center glow-primary">
                <Dumbbell className="w-7 h-7 text-primary-foreground" />
              </div>
            </div>
            <h1 className="text-3xl font-bold text-foreground mb-2">Your Personalized Workout Plan</h1>
            <p className="text-muted-foreground">Generated by HomeGym Expert System</p>
            <Button onClick={handleReset} variant="outline" className="mt-4 gap-2">
              <RotateCcw className="w-4 h-4" /> Start Over
            </Button>
          </div>

          {/* Metric Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
            <MetricCard title="WCS Score" value={result.wcs.wcsScore} subtitle="Complexity" icon={Brain} color="primary" />
            <MetricCard title="Volume Score" value={result.volumeScore} subtitle="Weekly" icon={Activity} color="secondary" />
            <MetricCard title="Est. Calories" value={result.estimatedCalorieBurn} subtitle="kcal/week" icon={Flame} color="warning" />
          </div>

          {/* Inference Log */}
          <div className="mb-8">
            <InferenceLog logs={result.inferenceLog} isExpanded={logExpanded} onToggle={() => setLogExpanded(!logExpanded)} />
          </div>

          {/* Workout Schedule */}
          <div className="mb-8">
            <WorkoutSchedule workoutPlan={result.workoutPlan} />
          </div>

          {/* Calculation Breakdown */}
          <CalculationBreakdown result={result} profile={profile} constraints={constraints} equipment={equipment} />
        </div>
      </div>
    );
  }

  // Wizard
  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="py-6 px-4 border-b border-border">
        <div className="max-w-4xl mx-auto flex items-center justify-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-primary to-cyan-400 flex items-center justify-center glow-primary">
            <Dumbbell className="w-6 h-6 text-primary-foreground" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-foreground">HomeGym Expert</h1>
            <p className="text-sm text-muted-foreground">AI-Powered Workout Planner</p>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 py-8 px-4">
        <div className="max-w-3xl mx-auto">
          <ProgressBar currentStep={currentStep} totalSteps={steps.length} steps={steps} />

          <div className="bg-card rounded-2xl border border-border p-6 md:p-8 shadow-lg">
            {currentStep === 0 && <Step1Profile profile={profile} onChange={setProfile} />}
            {currentStep === 1 && <Step2Constraints constraints={constraints} onChange={setConstraints} />}
            {currentStep === 2 && <Step3Equipment equipment={equipment} onChange={setEquipment} />}

            <WizardNavigation
              currentStep={currentStep}
              totalSteps={steps.length}
              onNext={handleNext}
              onBack={handleBack}
              onSubmit={handleSubmit}
              canProceed={canProceed()}
            />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="py-4 px-4 border-t border-border text-center text-sm text-muted-foreground">
        ISP543: Knowledge Based System • HomeGym Expert System v1.0
      </footer>
    </div>
  );
};

export default Index;
